# Generated by Django 3.1.6 on 2021-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=64)),
                ('date_input', models.CharField(max_length=64)),
                ('time_input', models.CharField(max_length=64)),
                ('date_time', models.CharField(max_length=64)),
            ],
        ),
    ]
