# Generated by Django 3.1.6 on 2021-04-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0002_auto_20210411_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
    ]
