# Generated by Django 3.1.6 on 2021-04-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0003_auto_20210411_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='SmartMC',
        ),
    ]
