# Generated by Django 3.1.6 on 2021-04-11 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0004_auto_20210411_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmc',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='smartmc',
            name='email',
            field=models.EmailField(default='hio', max_length=200),
            preserve_default=False,
        ),
    ]
