# Generated by Django 3.1.6 on 2021-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0006_auto_20210412_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_box', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='place_in',
            field=models.CharField(blank=True, choices=[('Pill Box-1', 'Pill Box-1'), ('Pill Box-2', 'Pill Box-2')], max_length=50, null=True),
        ),
    ]
