# Generated by Django 3.1.6 on 2021-04-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0008_auto_20210412_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmc',
            name='export_to_CSV',
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='place_in',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='table_creator.category'),
        ),
    ]
