# Generated by Django 3.1.6 on 2021-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0014_auto_20210412_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmc',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
