# Generated by Django 3.1.6 on 2021-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0015_auto_20210412_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmc',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please Enter your Full Name'),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='pill_Box1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True, verbose_name='Add the Box you want to store pill in '),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Pills you wish to take now'),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='total_quantity',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name=' Total Amount of Pills '),
        ),
    ]
