# Generated by Django 3.1.6 on 2021-04-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0017_smartmc_day_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmc',
            name='date',
        ),
    ]
