# Generated by Django 3.1.6 on 2021-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0009_auto_20210412_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmc',
            name='date_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
