# Generated by Django 3.1.6 on 2021-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0012_auto_20210412_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmc',
            name='pill_Box1',
            field=models.CharField(blank=True, choices=[('1', '1')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='pill_Box2',
            field=models.CharField(blank=True, choices=[('2', '2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='pill_Box3',
            field=models.CharField(blank=True, choices=[('3', '3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='pill_Box4',
            field=models.CharField(blank=True, choices=[('4', '4')], max_length=50, null=True),
        ),
    ]
