# Generated by Django 3.1.6 on 2021-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0016_auto_20210412_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmc',
            name='day_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please Enter the name of the day'),
        ),
    ]
