# Generated by Django 3.1.6 on 2021-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0019_smartmc_day_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmc',
            name='date_now',
        ),
        migrations.RemoveField(
            model_name='smartmc',
            name='email',
        ),
        migrations.AlterField(
            model_name='smartmc',
            name='day_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please Enter the time of the day in Hour:minutes format'),
        ),
    ]
