# Generated by Django 3.1.6 on 2021-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0020_auto_20210413_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmc',
            name='day_time',
            field=models.TimeField(null=True, verbose_name='Please Enter the time of the day in (Hour : minutes)  format'),
        ),
    ]
