# Generated by Django 3.1.6 on 2021-04-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_creator', '0007_auto_20210412_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmc',
            name='place_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table_creator.category'),
            preserve_default=False,
        ),
    ]
